name: Update & Build Meshtastic (SquirrelCore)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * *" # Daily at 6 AM UTC – optional

jobs:
  update-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git gh python3 python3-pip
          pip install -U platformio

      # 3. Fetch latest stable Meshtastic release
      - name: Fetch latest stable Meshtastic release
        run: |
          cd firmware
          rm -rf meshtastic
          LATEST_TAG=$(gh release list --repo meshtastic/firmware --limit 20 | grep -v "dev" | grep -m1 -oP '^v[0-9]+\.[0-9]+\.[0-9]+')
          echo "Using Meshtastic firmware tag: $LATEST_TAG"
          gh release download "$LATEST_TAG" --repo meshtastic/firmware --pattern 'source.tar.gz' --output meshtastic.tar.gz
          mkdir meshtastic
          tar -xzf meshtastic.tar.gz -C meshtastic --strip-components=1
          rm meshtastic.tar.gz

      # 4. Sync your custom SquirrelCore variant into Meshtastic
      - name: Sync custom variant
        run: |
          rsync -av --delete firmware/variants/SquirrelCore/ firmware/meshtastic/variants/SquirrelCore/

      # 5. Build the SquirrelCore firmware
      - name: Build firmware for SquirrelCore
        working-directory: firmware/meshtastic
        run: |
          echo "Building firmware for SquirrelCore..."
          platformio run -e SquirrelCore

      # 6. Upload firmware binaries as workflow artifacts
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SquirrelCore-firmware-${{ github.run_number }}
          path: |
            firmware/meshtastic/.pio/build/SquirrelCore/firmware.uf2
            firmware/meshtastic/.pio/build/SquirrelCore/firmware.bin
            firmware/meshtastic/.pio/build/SquirrelCore/firmware.elf

      # 7. (Optional) Commit firmware to firmware-builds branch
      - name: Commit firmware to firmware-builds branch
        if: success()
        run: |
          cd firmware/meshtastic
          mkdir -p ../../builds/${{ github.run_number }}
          cp .pio/build/SquirrelCore/firmware.* ../../builds/${{ github.run_number }}/

          cd ../../
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add builds/
          git commit -m "Add SquirrelCore firmware build #${{ github.run_number }}"
          git push origin HEAD:firmware-builds || echo "Branch push skipped (no changes or branch missing)"
