name: Update Meshtastic Firmware

on:
  workflow_dispatch:        # Allow manual trigger from the Actions tab
  schedule:
    - cron: '0 0 * * 1'     # Run weekly (every Monday at 00:00 UTC)

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Download latest stable Meshtastic release
        id: get_release
        uses: robinraju/release-downloader@v1
        with:
          repository: "meshtastic/firmware"
          latest: true
          preRelease: false         # This ensures we skip dev/nightly builds
          fileName: "*.zip"
          out-file-path: "firmware/meshtastic"

      - name: Unzip firmware
        run: |
          cd firmware/meshtastic
          unzip -o *.zip -d .
          rm *.zip

      - name: Apply custom variant folder
        run: |
          mkdir -p firmware/variants
          rsync -av firmware/variants/ firmware/meshtastic/variants/ --ignore-existing

      - name: Commit and push updated firmware
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add firmware/meshtastic
          git commit -m "Auto-update Meshtastic to latest stable release" || echo "No changes to commit"
          git push
