name: Update, Build, and Release SquirrelCore Firmware

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # daily at 6 AM UTC, optional

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:

      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git gh python3 python3-pip
          pip install -U platformio

      # 3. Fetch latest stable Meshtastic release
      - name: Fetch latest stable Meshtastic release
        id: meshtastic_release
        run: |
          mkdir -p firmware
          cd firmware
          rm -rf meshtastic
          LATEST_TAG=$(gh release list --repo meshtastic/firmware --limit 20 | grep -v "dev" | grep -m1 -oP '^v[0-9]+\.[0-9]+\.[0-9]+')
          echo "Latest Meshtastic release: $LATEST_TAG"
          echo "meshtastic_version=$LATEST_TAG" >> $GITHUB_OUTPUT
          gh release download "$LATEST_TAG" --repo meshtastic/firmware --pattern 'source.tar.gz' --output meshtastic.tar.gz
          mkdir meshtastic
          tar -xzf meshtastic.tar.gz -C meshtastic --strip-components=1
          rm meshtastic.tar.gz

      # 4. Sync SquirrelCore variant if present
      - name: Sync SquirrelCore variant (optional)
        run: |
          if [ -d "firmware/variants/SquirrelCore" ]; then
            echo "SquirrelCore variant found, copying..."
            rsync -av --delete firmware/variants/SquirrelCore/ firmware/meshtastic/variants/SquirrelCore/
          else
            echo "SquirrelCore variant folder not found, skipping build."
            exit 0
          fi

      # 5. Build SquirrelCore firmware
      - name: Build firmware for SquirrelCore
        working-directory: firmware/meshtastic
        run: |
          echo "Building firmware for SquirrelCore..."
          platformio run -e SquirrelCore

      # 6. Create GitHub Release if build succeeded
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "SquirrelCore-${{ steps.meshtastic_release.outputs.meshtastic_version }}"
          release_name: "SquirrelCore firmware ${{ steps.meshtastic_release.outputs.meshtastic_version }}"
          body: "Automated firmware build for SquirrelCore based on Meshtastic ${{ steps.meshtastic_release.outputs.meshtastic_version }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7. Upload firmware binaries to the release
      - name: Upload firmware assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            firmware/meshtastic/.pio/build/SquirrelCore/firmware.uf2
            firmware/meshtastic/.pio/build/SquirrelCore/firmware.bin
            firmware/meshtastic/.pio/build/SquirrelCore/firmware.elf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
