name: Build SquirrelCore Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # optional daily check at 03:00 UTC

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 python3-pip jq
          pip3 install platformio

      - name: Fetch latest stable Meshtastic release
        id: meshtastic
        run: |
          # Get latest stable tag (no dev)
          LATEST_TAG=$(git ls-remote --tags https://github.com/meshtastic/firmware.git \
            | awk -F/ '{print $3}' | grep -v "dev" | sort -V | tail -n1)
          echo "Latest Meshtastic release: $LATEST_TAG"
          echo "meshtastic_version=$LATEST_TAG" >> $GITHUB_OUTPUT

          # Clone the source at that tag
          git clone --branch $LATEST_TAG --depth 1 https://github.com/meshtastic/firmware.git meshtastic

      - name: Add SquirrelCore variant
        run: |
          mkdir -p meshtastic/variants/SquirrelCore
          cp -r variants/SquirrelCore/* meshtastic/variants/SquirrelCore/

      - name: Build SquirrelCore firmware
        run: |
          cd meshtastic
          pio run -e SquirrelCore

      - name: Release firmware if build succeeds
        uses: ncipollo/release-action@v1
        with:
          tag: SquirrelCore-${{ steps.meshtastic.outputs.meshtastic_version }}
          name: SquirrelCore ${{ steps.meshtastic.outputs.meshtastic_version }}
          files: meshtastic/.pio/build/SquirrelCore/firmware.bin
