- name: Get latest Meshtastic release and extract
  shell: bash
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    set -e

    # Get latest non-dev, non-revoked release
    RELEASE=$(gh release list --repo meshtastic/firmware --limit 20 --json tagName,name \
      | jq -r '.[] | select(.tagName | test("dev") | not) | select(.name | test("\\(Revoked\\)") | not) | .tagName' | head -n1)

    if [ -z "$RELEASE" ]; then
      echo "Error: Could not determine latest Meshtastic release!"
      exit 1
    fi

    echo "Latest Meshtastic release: $RELEASE"
    echo "meshtastic_version=$RELEASE" >> $GITHUB_OUTPUT

    # Download source if available, ignore failure
    gh release download "$RELEASE" --repo meshtastic/firmware \
      --pattern 'source.tar.gz' --output meshtastic.tar.gz || true

    # Extract if downloaded
    if [ -f meshtastic.tar.gz ]; then
      mkdir -p meshtastic
      tar -xzf meshtastic.tar.gz -C meshtastic --strip-components=1
      rm meshtastic.tar.gz
    else
      # Fallback: clone repo at release tag
      git clone --branch "$RELEASE" --depth 1 https://github.com/meshtastic/firmware.git meshtastic
    fi
